version: '3.9'
services:
  marco:
    container_name: Marco
    pull_policy: build
    build: https://github.com/BrackeysBot/Marco.git#main
    volumes:
      - type: bind
        source: /var/log/brackeysbot/marco
        target: /app/logs
      - type: bind
        source: /etc/brackeysbot/marco
        target: /app/data
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
